### ISSUE TITLE
[BUG][安全合规][云厂商][总览]饼图和柱状图中第一个字段名称重复显示

### ISSUE THREAD

**Issue by supersarah123** [CloudExplorer-Dev/CloudExplorer-Lite#105]
### CloudExplorer Lite 版本

v1.0.0

### 问题描述

安全合规中的总览页面饼图和柱状图中第一个字段名称重复显示

### 重现步骤

<img width="1395" alt="image" src="https://user-images.githubusercontent.com/45278450/234743157-dcf30bc8-7a3a-449b-8a24-443c46aac4e3.png">

**Comment by Shenguobin0102** [comment]
感谢反馈，已知问题，请关注后续版本。

**Comment by baixin513** [comment]
该issue已在v1.1.0版本中解决。
