### ISSUE TITLE
[QUESTION][模块名称][云厂商][功能菜单]问题描述

### ISSUE THREAD

**Issue by Kerberos201** [CloudExplorer-Dev/CloudExplorer-Lite#113]
### 请描述您的问题

aws，azure, Google cloud, oracle cloud 
可不可以？

**Comment by baixin513** [comment]
您好，上述云厂商目前还不支持。

**Comment by vvvsrx** [comment]
Azure平台用起来太复杂了,如果能对接Azure,然后方便的查看计费就好了

**Comment by baixin513** [comment]
国外的云平台在费用还涉及到汇率换算问题，每天汇率都不一样，对接起来相对复杂一些。
且支持一个云平台不光只对接费用，还有云服务、磁盘、监控等等一系列功能。咱们近期暂时是没规划。
