### ISSUE TITLE
[FEATURE][虚拟机创建] [私有云][流程]希望增加云主机新建/修改/删除等流程功能   有需求的可以在此issue下补充

### ISSUE THREAD

**Issue by bigbird1985** [CloudExplorer-Dev/CloudExplorer-Lite#118]
### CloudExplorer Lite 版本

1.02

### 请描述您的需求或者改进建议

1、希望增加虚拟机创建/修改/删除回收等流程审批功能
2、希望增加创建虚拟机过程的添加自定义脚本功能

**Comment by baixin513** [comment]
目前看来用户需求不是很多，关于流程审批功能我们近期没有规划，先将该issue关闭。
