### ISSUE TITLE
[FEATURE][安全合规]安全合规中的扫描检查

### ISSUE THREAD

**Issue by baalchina** [CloudExplorer-Dev/CloudExplorer-Lite#119]
### CloudExplorer Lite 版本

v1.0.2

### 请描述您的需求或者改进建议

今天新装的cloudexplorerlite，新加的vcenter，然后扫描之后出现一些不合规，提点建议：

1. 在扫描检查里有很多不合规的，点击扫描结果可以看到具体机器，但是初次使用并不知道他具体为啥不合规，比如
![image](https://user-images.githubusercontent.com/3983019/236395848-4540316c-0e6d-4159-afb2-3011240a6c93.png)
必须要找到这条规则才能查看具体原因，那么在上图这个地方可否设计成规则可以点击呢？这样方便一点。

2. 规则设置里，输入规则缺少一个查找按钮？（红框位置）
![image](https://user-images.githubusercontent.com/3983019/236396098-d3d26992-a459-478a-bf7d-c1f9eab5387d.png)

3. 这条规则的单位没有？
![image](https://user-images.githubusercontent.com/3983019/236396244-1cba18ff-5188-48cc-8351-9f5b5c891d6f.png)
这个300是300g还是？比如vmware，自带的磁盘一般很小，那可否改成百分比呢？比如小于30%
这个地方并不太好理解
![image](https://user-images.githubusercontent.com/3983019/236396376-45347970-83ac-452f-8e6b-341fdbf7f62d.png)

**Comment by baixin513** [comment]
感谢反馈，您的使用建议太赞了，我们会放入开发计划进行优化，请关注后续版本。
1、在扫描检查中点击规则名称，右侧弹抽屉显示具体的规则信息。
2、搜索框目前是回车生效，需要增加icon  🔍
3、VMware平台的存储器资源类型的剩余容量属性增加单位显示为：剩余容量（GB）

**Comment by baixin513** [comment]
该issue 在v1.1.0版本已解决。
