### ISSUE TITLE
平台部署太耗资源，建议优化

### ISSUE THREAD

**Issue by liuxinxin2020** [CloudExplorer-Dev/CloudExplorer-Lite#12]
### CloudExplorer Lite 版本

v1.0.0

### 请描述您的需求或者改进建议

4C8G根本跑不起来；

8C16G也经常挂掉；

建议进行优化

**Comment by baixin513** [comment]
感谢反馈，服务器最小配置推荐：8C16G， 若服务器是 VMware 虚拟机需要查一下配置是否真正的满足最小配置。
