### ISSUE TITLE
【需求建议】[云主机创建][VMware][云主机管理]【建议在创建云主机时选择模板页面中增加显示模板的“备注”字段】

### ISSUE THREAD

**Issue by luzhuang-design** [CloudExplorer-Dev/CloudExplorer-Lite#120]
### CloudExplorer Lite 版本

v1.0.1

### 请描述您的需求或者改进建议

建议在创建云主机时选择模板页面中增加显示模板的“备注”字段

### 请描述你建议的实现方案

在选择某个模板后，直接在右侧显示关于主机模板的备注信息（见附件截图）

### 附加信息

![image](https://user-images.githubusercontent.com/48269565/236411584-345e8ab0-da21-4b64-a7f1-a32bef2adbe5.png)
![image](https://user-images.githubusercontent.com/48269565/236411638-feecbd04-e7e8-4c41-9004-45bddc44c553.png)

**Comment by baixin513** [comment]
感谢反馈， 后面版本优化一下这块。

**Comment by baixin513** [comment]
该需求在v1.2.0版本已实现，欢迎使用。
