### ISSUE TITLE
[需求建议][用户管理][vmware][组织]对组织可以设置使用资源配额，防止过度使用资源。

### ISSUE THREAD

**Issue by zjp0706** [CloudExplorer-Dev/CloudExplorer-Lite#122]
### CloudExplorer Lite 版本

v1.0.1

### 请描述您的需求或者改进建议

1、对组织可以限定资源使用配额，比如使用多少cpu、内存、磁盘资源。一个vmware平台是多个部门共享的，为了防止某一个部门过度的使用vmware资源，给组织添加配额限定。在限定内各个组织自己管理自己的虚机情况，也杜绝了过度使用资源的情况，同时减少了vmware管理员的工作量。

### 请描述你建议的实现方案

方案1：给云账号下添加资源池的概念，一个云账号下可以划分多个资源池。将资源池和组织进行绑定。绑定后改组织的资源使用量不能超过改资源池。
方案2：在创建组织时，可以配置组织的使用配额，比如多少cpu、内存、磁盘等资源限额。该组织创建虚机时，重这个配额中扣除对应的配额。同样该组织不能超过资源限定。

**Comment by bigbird1985** [comment]
支持，我们也需要这个功能
