### ISSUE TITLE
[创建主机时模板list无排序规则][云主机创建][Vmware][云主机管理]创建主机时模板list排序混乱

### ISSUE THREAD

**Issue by luzhuang-design** [CloudExplorer-Dev/CloudExplorer-Lite#124]
### CloudExplorer Lite 版本

v1.0.1

### 问题描述

创建主机时模板list排序混乱
![image](https://user-images.githubusercontent.com/48269565/236618080-ecb3241e-8034-4cbd-8554-d886303acbaa.png)

### 重现步骤

直接在Vmware资源节点中（需要存在多个主机模板）创建主机，模板列表显示杂乱

### 期待的正确结果

按照一定规则形成列表显示：
1、按照数字排序
2、按照a-z字母排序

**Comment by bigbird1985** [comment]
顶，非常需要！

**Comment by baixin513** [comment]
该issue在v1.1.0版本中已解决。
