### ISSUE TITLE
[FEATURE]云主机到期提醒和回收资源

### ISSUE THREAD

**Issue by renziyou** [CloudExplorer-Dev/CloudExplorer-Lite#128]
### CloudExplorer Lite 版本

v1.0.2

### 请描述您的需求或者改进建议

需求：希望后面版本能增加【自服务的功能】
场景：目前我公司是私有云模式，开发人员申请服务器资源，我们根据资源进行开通，部分是用于测试。或部分是过时系统，系统已停用。这些服务器资源也没人通知是否可回收，导致大量服务器资源被浪费！！
要求：希望能像公有云那样，开发人员开通账号后，自助申请服务器资源及使用时长，后台审批通过后自动创建相关服务器。每个开发人员只能看到自己申请的服务器并拥有管理权限。待时间将到期时，提前一个月每天进行 通知提醒【发给申请人员及服务器后台管理人员】。如一个月内任未处理，将对服务器进行自动停机处理，15天后任未处理，对停用的自动销毁处理。

### 请描述你建议的实现方案

要求：希望能像公有云那样，开发人员开通账号后，自助申请服务器资源及使用时长，后台审批通过后自动创建相关服务器。每个开发人员只能看到自己申请的服务器并拥有管理权限。待时间将到期时，提前一个月每天进行 通知提醒【发给申请人员及服务器后台管理人员】。如一个月内任未处理，将对服务器进行自动停机处理，15天后任未处理，对停用的自动销毁处理。

**Comment by baixin513** [comment]
感谢反馈，针对私有云的云主机 近期考虑增加的功能是到期策略设置。
申请包月机器会有到期时间，到期前进行通知，到期后可设置策略是关机还是删除。

**Comment by bigbird1985** [comment]
有同样的需求，希望可以支持
