### ISSUE TITLE
[FEATURE]云账号同步资源频率设置限制最小时间

### ISSUE THREAD

**Issue by xueqidove** [CloudExplorer-Dev/CloudExplorer-Lite#13]
### CloudExplorer Lite 版本

1.0

### 请描述您的需求或者改进建议

云账号同步频率设置限制最小间隔同步时间，不得随意设置1分钟，容易导致因资源同步引起的各种问题，特别是资源数量比较大的情况

**Comment by baixin513** [comment]
感谢反馈，同步频率中间隔类型的值可以增加最小值限制，请关注后续版本更新。

**Comment by baixin513** [comment]
我们在V1.1.0中优化了该问题，同步频率间隔最小时间为15分钟。
