### ISSUE TITLE
[FEATURE]增加主机监控信息同步频率设置

### ISSUE THREAD

**Issue by xueqidove** [CloudExplorer-Dev/CloudExplorer-Lite#15]
### CloudExplorer Lite 版本

1.0

### 请描述您的需求或者改进建议

增加主机监控信息同步频率设置

**Comment by baixin513** [comment]
感谢反馈，该功能已规划，请关注后续版本。

**Comment by baixin513** [comment]
该功能在V1.2.0版本实现，欢迎试用。
