### ISSUE TITLE
[FEATURE]开启回收站功能描述不准确

### ISSUE THREAD

**Issue by xueqidove** [CloudExplorer-Dev/CloudExplorer-Lite#16]
### CloudExplorer Lite 版本

1.0

### 请描述您的需求或者改进建议

回收站策略中的开启回收站功能说明，在最后建议补充指导用户放入回收站内的机器如何被彻底删除释放
<img width="653" alt="image" src="https://user-images.githubusercontent.com/60059766/232945481-73185968-deb6-4163-8d5c-b1c829b78665.png">

**Comment by baixin513** [comment]
感谢反馈，后续版本会优化该提示。

**Comment by baixin513** [comment]
该问题已在V1.0.2版本解决，欢迎使用。
