### ISSUE TITLE
[FEATURE][安装部署]建议程序部署的安装配置install.conf增加内存、cpu等资源限制参数

### ISSUE THREAD

**Issue by learnzpk** [CloudExplorer-Dev/CloudExplorer-Lite#167]
### CloudExplorer Lite 版本

1.0.2

### 请描述您的需求或者改进建议

使用一段时间后很容易出现内存爆炸的情况，导致页面访问不流畅或者无法访问。
建议安装脚本能根据配置install.conf限制每个容器的内存上限。
![image](https://github.com/CloudExplorer-Dev/CloudExplorer-Lite/assets/30232608/07e33191-c9aa-40de-a16e-62b6d05f9e6a)

**Comment by ulleo** [comment]
是个好建议，我们后续优化一下

**Comment by baixin513** [comment]
该功能在V1.2.0版本中实现，欢迎试用。
