### ISSUE TITLE
[BUG][安全合规][阿里云][扫描检查]未正确给出对是否打了指定标签的扫描结果

### ISSUE THREAD

**Issue by liuxinxin2020** [CloudExplorer-Dev/CloudExplorer-Lite#169]
### CloudExplorer Lite 版本

v1.1.0-pre

### 问题描述

对打了【测试环境】（标签值）的安全组进行扫描；
希望扫描的结果是打了【测试环境】或【生产环境】标签值的安全组为合规；
结果某安全组实际打了【测试环境】的标签，但扫描结果依然为不合规。

### 重现步骤

1、设置如下扫描规则：
<img width="1456" alt="image" src="https://github.com/CloudExplorer-Dev/CloudExplorer-Lite/assets/72063838/c56eac0f-7a1d-4ab2-81ec-a7466178c971">

2、云平台该资源打如下标签：
<img width="1267" alt="image" src="https://github.com/CloudExplorer-Dev/CloudExplorer-Lite/assets/72063838/f177407c-9bf6-4d72-b6b2-6455b417cc8e">

3、进行扫描，并查看扫描结果
<img width="1474" alt="image" src="https://github.com/CloudExplorer-Dev/CloudExplorer-Lite/assets/72063838/7f063dc0-c6d7-49ea-917e-eb86dd5a0e14">

**Comment by liuxinxin2020** [comment]
重现步骤中1和3的图需要颠倒一下

**Comment by liuxinxin2020** [comment]
对阿里云的ECS资源进行上述扫描，也有上述问题。

**Comment by baixin513** [comment]
感谢反馈，已修复。
