### ISSUE TITLE
[BUG][安全合规][阿里云][总览]删除云账号后，安全合规中的数据没有同步清理掉（对应之前提交关闭的#65）

### ISSUE THREAD

**Issue by liuxinxin2020** [CloudExplorer-Dev/CloudExplorer-Lite#179]
### CloudExplorer Lite 版本

v1.1.0

### 问题描述

<img width="849" alt="image" src="https://github.com/CloudExplorer-Dev/CloudExplorer-Lite/assets/72063838/de2c59c5-a24f-4f43-8a0b-f574f193d343">

### 重现步骤

1、管理中心中删除云账号；
2、来到安全合规模块，查看总览中的数据。

### 期待的正确结果

删除云账号后，安全合规中不应该再看到已删除云账号的数据。

**Comment by Shenguobin0102** [comment]
问题已确认，会尽快处理。

**Comment by baixin513** [comment]
感谢反馈，该问题在v1.2.0版本中已解决。
