### ISSUE TITLE
[FEATURE] VMware 主机申请添加数据磁盘时能够有最小值以及步长限制

### ISSUE THREAD

**Issue by xueqidove** [CloudExplorer-Dev/CloudExplorer-Lite#18]
### CloudExplorer Lite 版本

1.0

### 请描述您的需求或者改进建议

VMware 主机申请添加数据磁盘时能够有最小值以及步长限制，不建议随意写数据盘大小
<img width="700" alt="image" src="https://user-images.githubusercontent.com/60059766/232953509-348f8684-4a09-48bc-8393-562391ac6bb9.png">

**Comment by baixin513** [comment]
感谢反馈，当前最小值处理是保持和各云平台一致的。步长值可优化为10。

**Comment by baixin513** [comment]
该issue在V1.1.0中已解决。
