### ISSUE TITLE
[BUG][管理中心][日志管理：操作日志、系统日志]升级到v1.1.0版本后，历史的操作日志、系统日志信息都丢失了

### ISSUE THREAD

**Issue by liuxinxin2020** [CloudExplorer-Dev/CloudExplorer-Lite#181]
### CloudExplorer Lite 版本

v1.1.0

### 问题描述

[BUG][管理中心][日志管理：操作日志、系统日志]升级到v1.1.0版本后，历史的操作日志、系统日志信息都丢失了

### 重现步骤

[BUG][管理中心][日志管理：操作日志、系统日志]升级到v1.1.0版本后，历史的操作日志、系统日志信息都丢失了

**Comment by baixin513** [comment]
感谢反馈，该问题已在v1.2.0版本中解决。
