### ISSUE TITLE
[FEATURE][运营分析][云主机优化]优化保留的小数点位数依然不统一

### ISSUE THREAD

**Issue by liuxinxin2020** [CloudExplorer-Dev/CloudExplorer-Lite#182]
保留的小数点位数依然不统一
<img width="1476" alt="image" src="https://github.com/CloudExplorer-Dev/CloudExplorer-Lite/assets/72063838/434443dc-9dae-4ecf-a8ee-835cf5e82e46">

_Originally posted by @liuxinxin2020 in https://github.com/CloudExplorer-Dev/CloudExplorer-Lite/issues/28#issuecomment-1560548094_

**Comment by Shenguobin0102** [comment]
问题已确认，会尽快处理。

**Comment by baixin513** [comment]
该问题已在v1.2.0中解决，感谢反馈，
