### ISSUE TITLE
[FEATURE][云账号][公有云]希望能支持一下AWS云的管理

### ISSUE THREAD

**Issue by sky111111** [CloudExplorer-Dev/CloudExplorer-Lite#186]
### CloudExplorer Lite 版本

v1.1.0

### 请描述您的需求或者改进建议

我们这里也使用到AWS云，而且国内不少公司都有对AWS云的使用，希望能支持对于AWS云的管理

**Comment by baixin513** [comment]
想要了解下：您这边用的是AWS的国内云还是国外云？

**Comment by songkingkong** [comment]
我也有同样的需求，我理解AWS主要是在国外使用，另外goole云(GCP)其实也会用到

**Comment by baixin513** [comment]
感谢反馈，经过讨论，近期内不会支持，如有需要可以了解一下商业版云管，该ISSUE将被关闭。
