### ISSUE TITLE
云账号与组织架构绑定关联关系

### ISSUE THREAD

**Issue by xiaoluyahei** [CloudExplorer-Dev/CloudExplorer-Lite#19]
### CloudExplorer Lite 版本

V1.0.0

### 请描述您的需求或者改进建议

在企业环境中，因为多地多业务的场景，会存在多套Vsphere环境，每套的环境大约有1000+的虚拟机。希望云账号与组织之间存在绑定的关联关系，如果这样的话，在Vsphere平台中创建了一台新的虚拟机，cloudexplorer平台自动同步发现新增的虚拟机，就可以把新的主机根据绑定关联关系，自动分类到对应的组织中，便于后期维护。

**Comment by baixin513** [comment]
感谢反馈，一般云账号纳管到云管理平台中后，资源的运维管理操作是希望统一在云管平台中进行操作的， 不建议用户在运管平台和Vsphere平台中同时操作。

云管平台的顶部导航栏可以切换组织，租户分配了组织权限，在对应组织中创建云主机 ，云主机会默认关联当前所在的组织。不知能否满足您的需求。
<img width="1393" alt="image" src="https://user-images.githubusercontent.com/52996290/233009427-6f857adc-5f0b-4d24-b39f-70a4b38f87a4.png">

**Comment by xiaoluyahei** [comment]
在初次接入云账号的时候，存量的主机就不会自动归类到组织架构中，需要后续手动授权。所以能考虑一下云账号和组织之间存在一种授权关联关系

**Comment by baixin513** [comment]
感谢建议！
纳管云账号同步资源后，仅需一次手动授权，操作频率不高，后续定时同步都会默认按照该授权关联组织。

另一方面，假设云账号与组织设置了自动授权规则，页面上还是可以操作手动授权，会导致授权冲突。
再有，其他组织下的用户选择了这个云账号创建了资源，资源所属组织就可能会乱掉。

**Comment by xiaoluyahei** [comment]
ok
