### ISSUE TITLE
[FEATURE][运营分析][云主机优化]的列表信息，希望能支持导出excel

### ISSUE THREAD

**Issue by sky111111** [CloudExplorer-Dev/CloudExplorer-Lite#193]
### CloudExplorer Lite 版本

v1.1.0

### 请描述您的需求或者改进建议

云主机优化的发现的待优化主机信息，希望能支持导出，这样便于团队之间传递沟通

**Comment by baixin513** [comment]
感谢反馈，该功能在近期开发，请关注后续版本。

**Comment by baixin513** [comment]
感谢反馈，该需求在v1.2.0中解决。
