### ISSUE TITLE
[FEATURE][云主机][阿里云][创建主机]支持设置密钥/支持选择自定义镜像

### ISSUE THREAD

**Issue by jC8WbQ2cH4ymFBk** [CloudExplorer-Dev/CloudExplorer-Lite#194]
### CloudExplorer Lite 版本

v1.1.0

### 请描述您的需求或者改进建议

创建主机改进建议：
1、增加调用阿里云上设置的“密钥”

2、增加支持自定义镜像，自定义镜像已经做了很多定制，而阿里云自带的还创建机器后还需要DIY初始化。

3、要是能跟jump集成就完美啦。。。

**Comment by baixin513** [comment]
感谢反馈，第1、2点我们后面版本规划时会考虑实现，关注后续版本。
