### ISSUE TITLE
[FEATURE][云账单][账单总览][账单汇总]账单展示页未显示完全

### ISSUE THREAD

**Issue by 1499861469** [CloudExplorer-Dev/CloudExplorer-Lite#196]
### CloudExplorer Lite 版本

1.1.0

### 请描述您的需求或者改进建议

![image](https://github.com/CloudExplorer-Dev/CloudExplorer-Lite/assets/32377969/4c79f7ee-d9b4-4a25-9704-7d326792a525)
账单数组过长显示为省略号

**Comment by baixin513** [comment]
该问题已在v1.2.0版本中解决，感谢反馈。
