### ISSUE TITLE
[公有云][功能菜单]其他云产品的支持计划。

### ISSUE THREAD

**Issue by xududu** [CloudExplorer-Dev/CloudExplorer-Lite#197]
### CloudExplorer Lite 版本

v1.1.0

### 请描述您的需求或者改进建议

有没有对其他云产品纳管和统计的计划。比如各个公有云的对象存储服务。

### 请描述你建议的实现方案

类似云主机的展示方式，可以统一查看对象存储的使用情况。

**Comment by baixin513** [comment]
有计划支持，但需要耐心等待一些时间。

**Comment by baixin513** [comment]
感谢反馈，经讨论后，近期内无法支持，该ISSUE将会关闭。
