### ISSUE TITLE
【云主机管理】创建VMware云主机的资源配置中资源池列表增加搜索功能

### ISSUE THREAD

**Issue by xiaoluyahei** [CloudExplorer-Dev/CloudExplorer-Lite#20]
### CloudExplorer Lite 版本

V1.0.0

### 请描述您的需求或者改进建议

![aaa](https://user-images.githubusercontent.com/131225593/232975779-553b0009-4e53-4f07-8474-08cb46542e29.png)

**Comment by baixin513** [comment]
感谢反馈，您的建议已采纳，请关注后续版本。

**Comment by xiaoluyahei** [comment]
ok

**Comment by baixin513** [comment]
该issue已在v1.1.0版本中解决。
