### ISSUE TITLE
希望增加资源分配功能及普通用户创建主机时增加时长【用户反馈非常强烈希望能纳入开发计划】

### ISSUE THREAD

**Issue by renziyou** [CloudExplorer-Dev/CloudExplorer-Lite#201]
### CloudExplorer Lite 版本

laste

### 请描述您的需求或者改进建议

需求一：
系统管理员可以针对项目或人员，进行资源分配。这样项目成员或普通人员，进行任意创建N台虚拟机，只要不超过分配的资源。

需求二：
项目成员或普通人员，在创建虚拟机，支持虚拟机使用时长设置，如临近过期提前一个月或自定时间每天倒计时推送续期通知到创建人及系统管理员，如超过时间未处理，就自动关机，若关机一个月后仍未处理就自动回收资源，减少僵尸虚拟机，减少资源浪费

**Comment by baixin513** [comment]
感谢反馈！
需求1：配额限制，限制组织/工作空间内的资源配额。
需求2：支持对机器设置到期时间。
需求3：到期策略：支持到期前通知，到期后关机或回收操作。
以上需求，后期功能版本迭代中会有计划实现，请耐心等待一下。

**Comment by GloamingCN** [comment]
支持需求，希望尽快update！
