### ISSUE TITLE
运营分析-云主机分析，增加历史已删除云主机的资源分析

### ISSUE THREAD

**Issue by cjx2022** [CloudExplorer-Dev/CloudExplorer-Lite#225]
### CloudExplorer Lite 版本

v1.2.0

### 请描述您的需求或者改进建议

当前云监控，可以看到已删除云主机的历史数据，说明历史云主机的监控指标数据是可展示的；
当前云主机分析内，无法筛选已删除主机，无法对历史云主机进行分析。

### 请描述你建议的实现方案

建议根据云主机历史监控数据，在云主机分析模块，添加对已删除历史云主机的资源分析。

**Comment by baixin513** [comment]
感谢反馈，想了解下这边的使用场景：
1、为什么会对已删除的机器分析 ？
2、想分析出什么样的数据？

**Comment by baixin513** [comment]
感谢反馈，想了解下这边的使用场景：
1、为什么会对已删除的机器分析 ？
2、想分析出什么样的数据？

**Comment by cjx2022** [comment]
> 感谢反馈，想了解下这边的使用场景： 1、为什么会对已删除的机器分析 ？ 2、想分析出什么样的数据？

1、云资源为了节省成本用完就删除，而资源的分析是滞后的，资源用完了才能对资源做整体的分析，同时历史数据也作为运营分析的依据必不可少。这个和使用场景无关，除非不做资源的整体运营分析。
2、当前已有的使用率分布也行，或者进一步类似云监控数据的看板，按照云账号、企业项目做使用率的整合图

**Comment by baixin513** [comment]
好的，大致了解了。
当前：运营分析-云主机分析-云主机按使用率分配中有汇总记录每个使用率范围内的云主机数量（历史删除的也会被统计上）。
后面可以再丰富一下各维度的分析及明细查看。
<img width="1430" alt="image" src="https://github.com/CloudExplorer-Dev/CloudExplorer-Lite/assets/52996290/1b9abc4b-ed16-4e50-9cd5-8ef5e01d78af">
