### ISSUE TITLE
希望可以增加个统计字段选项统计：应付金额、代金券抵扣、实付金额

### ISSUE THREAD

**Issue by hdsfgsgrlsgtw12** [CloudExplorer-Dev/CloudExplorer-Lite#227]
### CloudExplorer Lite 版本

v1.2.0

### 请描述您的需求或者改进建议

1、希望可以增加个统计字段选项统计：应付金额、代金券抵扣、实付金额。如下：
因为我们这边结算费用，有的会用代金券付，有的会用现金支付。
<img width="430" alt="image" src="https://github.com/CloudExplorer-Dev/CloudExplorer-Lite/assets/45323722/1d1b1fee-ee2a-486b-8018-d28f3d81c329">

2、现在平台只能创建阿里云主机，功能有点单一，希望可以增加创建rds，redis，dns，slb，acr等这些

**Comment by baixin513** [comment]
感谢反馈
1、账单统计后期版本计划会增加个字段选项统计：应付金额、代金券抵扣、实付金额等。
2、各类资源管理后期会逐步增加。需要耐心等待下。

**Comment by baixin513** [comment]
第一个点我们规划在V1.4.0中支持。
