### ISSUE TITLE
[FEATURE][模块名称][云厂商][功能菜单]需求描述 希望未来可以添加VMware5.5版本支持

### ISSUE THREAD

**Issue by jcwd061** [CloudExplorer-Dev/CloudExplorer-Lite#228]
### CloudExplorer Lite 版本

v1.2.0

### 请描述您的需求或者改进建议

当前版本添加VMware5.5失败，希望未来可以添加VMware5.5版本支持

**Comment by baixin513** [comment]
感谢反馈，我们当前是在7.0版本及以上环境开发测试的，所以暂时支持的7.0及以上版本，针对VMware5.5版本近期暂时还没有计划，后期若用户反馈需求强烈也会考虑支持。
