### ISSUE TITLE
[FEATURE]建议支持三大运营商的云

### ISSUE THREAD

**Issue by ziisp** [CloudExplorer-Dev/CloudExplorer-Lite#229]
### CloudExplorer Lite 版本

1.2.0

### 请描述您的需求或者改进建议

建议支持三大运营商的云

**Comment by bigbird1985** [comment]
建议支持移动云

**Comment by qiukaiclub** [comment]
建议支持移动云+1

**Comment by baixin513** [comment]
感谢反馈，经过讨论，近期内无法支持，如有需要，可以了解下商业版云管，该ISSUE将会关闭
