### ISSUE TITLE
[FEATURE][云账单][VMware][功能菜单]账单明细增加按天筛选

### ISSUE THREAD

**Issue by bigbird1985** [CloudExplorer-Dev/CloudExplorer-Lite#233]
### CloudExplorer Lite 版本

1.2

### 请描述您的需求或者改进建议

希望账单明细增加按天筛选；

**Comment by baixin513** [comment]
好的，感谢反馈，我们后面优化一下这个日期筛选组件。关注后续版本。

**Comment by baixin513** [comment]
该需求在v1.4.0版本中实现，请升级到最新版本。
