### ISSUE TITLE
一键安装脚本报错

### ISSUE THREAD

**Issue by qw4285632q** [CloudExplorer-Dev/CloudExplorer-Lite#235]
### 请描述您的问题

版本：cloudexplorer-online-installer-v1.2.0
安装命令：bash install.sh
报错截图：
![image](https://github.com/CloudExplorer-Dev/CloudExplorer-Lite/assets/27714601/d4fc5fbf-aaf4-446c-a4bc-b50342de2ea3)

**Comment by Shenguobin0102** [comment]
你好，根据报错信息判断，可能是 Docker 版本不兼容的问题，麻烦你提供一下服务器的 Docker 版本，或者完全卸载本地 Docker 及docker compose 后重新执行安装脚本再试一下。

**Comment by qw4285632q** [comment]
docker version:
![image](https://github.com/CloudExplorer-Dev/CloudExplorer-Lite/assets/27714601/23f6be7d-af89-4bd1-95f6-f5d394e8a1d2)
docker-compose: Docker Compose version v2.17.0-rc.1

**Comment by ulleo** [comment]
你好，这边我们测试了一下，应该是你这边的compose版本v2.17.0-rc.1的问题，你换成稳定的v2.17.0就没问题了

**Comment by qw4285632q** [comment]
如果启动配置文件设置的CE_BASE=/data  但是spring.redis.redisson.file 配置文件引用了改配置，导致容器启动内部寻找/data目录导致程序启动失败

**Comment by ulleo** [comment]
感谢反馈，这个问题之前没有注意到，你这边可以将cloudexplorer.properties文件内的spring.redis.redisson.file配置注释掉

**Comment by qw4285632q** [comment]
镜像mysql8.0 存在初始化参数lower_case_table_names 不生效问题。导致服务挂死。建议在mysql容器编译的时候就修改好

**Comment by ulleo** [comment]
> 镜像mysql8.0 存在初始化参数lower_case_table_names 不生效问题。导致服务挂死。建议在mysql容器编译的时候就修改好

没有遇到你说的这个问题呢，你这边 mysql 挂载的 my.cnf 路径正确的话应该不会有问题

**Comment by qw4285632q** [comment]
软件版本：[registry.cn-qingdao.aliyuncs.com/cloudexplorer/cloudexplorer-core:v1.2.0](http://registry.cn-qingdao.aliyuncs.com/cloudexplorer/cloudexplorer-core:v1.2.0)
组件：离线安装自带es logstash redis 使用了外部mysql8.0.30
现象： wen界面添加云账号选择 vmware ，属于vcenter7.0.3版本的远程账号密码，连接校验：云账号有效。
但是同步状态一直处于初始化状态：
![image](https://github.com/CloudExplorer-Dev/CloudExplorer-Lite/assets/27714601/66dc3b09-1b21-4e0f-8b85-95c2e71f0507)
手动点击同步，无任何资源可选择：
![image](https://github.com/CloudExplorer-Dev/CloudExplorer-Lite/assets/27714601/3ab4055b-57d3-4f73-81e1-6d0a17833862)
日志文件：/opt/cloudexplorer/logs/management-center info/error 日志
[info.log](https://github.com/CloudExplorer-Dev/CloudExplorer-Lite/files/12079368/info.log)
[error.log](https://github.com/CloudExplorer-Dev/CloudExplorer-Lite/files/12079370/error.log)

**Comment by qw4285632q** [comment]
补充vmware组件报错：
[info (1).log](https://github.com/CloudExplorer-Dev/CloudExplorer-Lite/files/12079653/info.1.log)

**Comment by Shenguobin0102** [comment]
您好，日志文件已收到，还需要麻烦您提供以下三个信息：
1.您的服务器配置信息，CPU、内存等；
2.使用 cectl status 命令查看一下其他模块的状态，包括 vm-service、security-compliance、operation-analysis、finance-management
3.请提供一下/opt/cloudexplorer/logs目录下的management-center-console.log、vm-service-console.log文件

**Comment by baixin513** [comment]
您好，未收到您这边的反馈，该issue我们关闭了，如果使用有问题请加入我们的技术交流群进行反馈。
