### ISSUE TITLE
[FEATURE]希望增加AWS支持，包括中国区和Global区

### ISSUE THREAD

**Issue by Litt1ekoala** [CloudExplorer-Dev/CloudExplorer-Lite#238]
### CloudExplorer Lite 版本

1.2

### 请描述您的需求或者改进建议

希望增加AWS支持，包括中国区和Global区

**Comment by baixin513** [comment]
感谢反馈，经过讨论该需求近期内无法支持，如有需要可以了解下商业版云管，该ISSUE将会关闭。
