### ISSUE TITLE
[云主机][VMware][云主机]创建VMware云主机时支持不选集群

### ISSUE THREAD

**Issue by lvtao-net** [CloudExplorer-Dev/CloudExplorer-Lite#239]
### CloudExplorer Lite 版本

latest

### 问题描述

esxi6.7服务器，单机，没有集群
添加到 CloudExplorer后，无法开通主机

### 重现步骤

添加单机esxi服务器

然后开通主机，集群位置灰色不可选，导致无法正常开通主机

### 期待的正确结果

无集群状态的esxi可开通

**Comment by baixin513** [comment]
感谢反馈，该问题我们在1.4.0版本解决，请关注后续版本。
