### ISSUE TITLE
[FEATURE][模块名称][云厂商][功能菜单]支持云主机告警通知

### ISSUE THREAD

**Issue by smaillong001** [CloudExplorer-Dev/CloudExplorer-Lite#241]
### CloudExplorer Lite 版本

V1.3.0

### 请描述您的需求或者改进建议

增加云主机告警规则及监控告警功能
具体可参考腾讯多云管理

### 请描述你建议的实现方案

增加云主机 CPU 、内存、磁盘 、网络等告警规则
资源类型：支持选择云主机、云硬盘、网络及内存。
规则内容：为指标、比较关系、阈值、告警规则及告警频率组成的一个有语义的条件。最多同时存在3条。
例如，指标为 CPU 利用率 、比较关系为> 、阈值为80% 、告警规则为连续5分钟、告警频率为每5分钟告警一次。
表示：若 CPU 利用率连续5分钟大于80%，则触发告警，每5分钟发送一次告警通知。

### 附加信息

[https://qcloudimg.tencent-cloud.cn/image/document/80b965555077d7b53e79638b5990a4d8.png](url)

**Comment by baixin513** [comment]
感谢反馈，告警是基于监控数据，当前的监控数据是通过各云平台的API获取的，各云平台对API访问频率进行的限制，所以在时间上有一定的延迟。告警这块我们需要在综合的讨论一下，近期安排不上开发计划。

**Comment by baixin513** [comment]
感谢反馈，经过讨论该需求近期内无法支持，如有需要可以了解下商业版云管，该ISSUE将会关闭。
