### ISSUE TITLE
[FEATURE]支持Zstack云平台反馈

### ISSUE THREAD

**Issue by liwg1995** [CloudExplorer-Dev/CloudExplorer-Lite#249]
### CloudExplorer Lite 版本

v1.3.0

### 请描述您的需求或者改进建议

希望增加Zstack这个私有云的接入及管理

### 请描述你建议的实现方案

对接Zstack厂商的接口，形成相关接入插件，来实现

**Comment by baixin513** [comment]
感谢反馈，我们先记录了，但近期不会安排计划支持。

**Comment by liwg1995** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
