### ISSUE TITLE
[QUESTION][添加AKSK][阿里云][功能菜单]问题描述 提示时间错误

### ISSUE THREAD

**Issue by bambooqj** [CloudExplorer-Dev/CloudExplorer-Lite#253]
### 请描述您的问题

 The input parameter "Timestamp" that is mandatory for processing this request is not supplied. request id

阿里云接口提示这个,是我本地测试问题,还是转换问题..

**Comment by bambooqj** [comment]
要在 CentOS 上将时区设置为上海（GMT+8），可以按照以下步骤进行操作：

1. 使用以下命令安装 `tzdata` 包：

```shell
yum install -y tzdata
```

2. 设置时区为上海。使用以下命令设置时区：

```shell
timedatectl set-timezone Asia/Shanghai
```

3. 验证时区设置。运行以下命令来验证时区是否已成功设置为上海：

```shell
timedatectl
```

在输出中，你应该看到 "Timezone: Asia/Shanghai"。

4. 更新系统时间。使用以下命令更新系统时间：

```shell
yum install -y chrony
systemctl start chronyd
systemctl enable chronyd
chronyc sources
```

这将使用 NTP（网络时间协议）从时间服务器同步系统时间。

现在，你的 CentOS 系统的时区应该已经设置为上海（GMT+8）。

**Comment by baixin513** [comment]
感谢反馈，看问题描述是已经解决了？

**Comment by thesmallants** [comment]
大佬，可以加个联系方式吗?找了您好久
