### ISSUE TITLE
[FEATURE][模块名称][云厂商][功能菜单]需求描述

### ISSUE THREAD

**Issue by chenbucheni** [CloudExplorer-Dev/CloudExplorer-Lite#254]
### CloudExplorer Lite 版本

v1.3.1

### 请描述您的需求或者改进建议

希望能增加证书管理功能，同步各个云平台域名到期证书；另外还有云主机同步jumpserver功能

**Comment by baixin513** [comment]
感谢反馈，近期支持不了。
