### ISSUE TITLE
建议支持金山云和火山引擎

### ISSUE THREAD

**Issue by liuhryme** [CloudExplorer-Dev/CloudExplorer-Lite#255]
### CloudExplorer Lite 版本

无

### 请描述您的需求或者改进建议

金山云：https://www.ksyun.com/；
火山引擎：https://www.volcengine.com/?utm_source=5&utm_medium=sembaidu&utm_term=sem_baidu_vg_pinzhuan_01&utm_campaign=vgbdpzztnA003&utm_content=guanwang

**Comment by baixin513** [comment]
感谢反馈，我们先记录了，但近期无计划支持。
