### ISSUE TITLE
[QUESTION]是否有计划支持oVirt?

### ISSUE THREAD

**Issue by charnet1019** [CloudExplorer-Dev/CloudExplorer-Lite#257]
### 请描述您的问题

由于openstack部署维护复杂，但很多小公司用的oVirt相对多点，目前用的比较多的版本是 4.4.10和4.5.4
是否有计划支持接入oVirt?
感谢。

**Comment by baixin513** [comment]
感谢反馈，近期还没有计划支持，但当前最新版本已经支持了 PVE。
