### ISSUE TITLE
[BUG][运营分析][OpenStack][资源分析]添加了Openstack集群后，资源分析里面的图标都没有数据

### ISSUE THREAD

**Issue by Payton443** [CloudExplorer-Dev/CloudExplorer-Lite#260]
### CloudExplorer Lite 版本

v1.4.0

### 问题描述

一开始添加了vCenter后，资源分析里面各个子菜单里面的图表数据都是正常的。添加了Openstack集群(Y版本)后，资源分析里面的图表都没有数据

### 重现步骤

1、添加openstack集群
2、点开资源分析-基础资源分析进行查看

### 期待的正确结果

正确显示图标

**Comment by baixin513** [comment]
具体没有数据的展示情况请截个图？还需要您截图看一下同步有没有报错信息？资源分析-明细表中有没有数据？
