### ISSUE TITLE
[FEATURE][vm-service[vmware][创建云主机]创建云主机时支持通过选择数据存储集群创建云主机

### ISSUE THREAD

**Issue by bigbird1985** [CloudExplorer-Dev/CloudExplorer-Lite#261]
### CloudExplorer Lite 版本

1.4

### 请描述您的需求或者改进建议

目前创建云主机只支持通过指定具体数据存储来创建，需要支持通过选择数据存储集群创建云主机

**Comment by baixin513** [comment]
感谢反馈，我们记录一下，后面排期优化一下。
