### ISSUE TITLE
[FEATURE][运营分析][vmware][基础资源分析]运营分析模块页面支持导出为excel

### ISSUE THREAD

**Issue by bigbird1985** [CloudExplorer-Dev/CloudExplorer-Lite#262]
### CloudExplorer Lite 版本

1.4

### 请描述您的需求或者改进建议

希望 运营分析模块，宿主机明细、存储器明细等页面支持导出为excel，方便详细分析和汇报

**Comment by baixin513** [comment]
感谢反馈，该需求已在v1.4.1版本实现，请升级至v1.4.1版本使用。
