### ISSUE TITLE
[QUESTION][模块名称][云厂商][功能菜单]问题描述

### ISSUE THREAD

**Issue by echo-ydj** [CloudExplorer-Dev/CloudExplorer-Lite#263]
### 请描述您的问题

在云账户中添加对应公有云账户,添加腾讯云账户,显示账户状态正常,但是无法同步账单及主机信息. 添加阿里云账户,检查对应账户,账户状态有时正常有时失败,并且无法同步主机及账单信息.
我应该怎么处理,对应的日志位置在哪块?
![image](https://github.com/CloudExplorer-Dev/CloudExplorer-Lite/assets/43643758/8a96fb3c-e08e-442e-8329-a3c6064284fb)

**Comment by baixin513** [comment]
您好，日志在/opt/cloudexplorer/logs/  
看一下哪个资源同步失败，云主机同步失败看一下 vm-service-console.log
云账单同步失败看一下fiance-management-console.log

鼠标放同步状态fail 上可以看到具体哪个资源同步失败。
