### ISSUE TITLE
[QUESTION]createModule方法如何执行

### ISSUE THREAD

**Issue by main1015** [CloudExplorer-Dev/CloudExplorer-Lite#265]
### 请描述您的问题

执行 createModule() 方法，等待执行完成，即会在services目录下根据模版创建出新的模块。
这个方法如何执行啊，我将代码clone到本地，通过[环境准备](https://fit2cloud.com/cloudexplorer-lite/docs/dev_manual/dev_manual_prepare/)将环境准备好了，但是在[新增一个扩展模块](https://fit2cloud.com/cloudexplorer-lite/docs/dev_manual/dev_manual_new_module/)里面通过执行 createModule() 方法，此时我不知道怎么操作了，我在demo目录下通过`mvn test`或者`mvn test -Dtest=CreateModuleUtil`都无法执行createModule方法，我想问问这个要怎么操作

**Comment by shaohuzhang1** [comment]
项目使用idea工具
![image](https://github.com/CloudExplorer-Dev/CloudExplorer-Lite/assets/80892890/415e93ff-ffdc-49a8-8e0f-5c5f95d71149)

**Comment by main1015** [comment]
我使用的是vscode idea，

其他文件的test方法就有这个可以执行的按钮
![image](https://github.com/CloudExplorer-Dev/CloudExplorer-Lite/assets/3272281/2b8c67f8-b4a8-466f-a7d0-9cf711a8cb3c)
但是CreateModuleUtil.java的createModule方法就没有这个按钮
![image](https://github.com/CloudExplorer-Dev/CloudExplorer-Lite/assets/3272281/3c0d7d05-edb3-4175-bbfd-061c42da7271)


并且这个不能再命令行下执行吗？

**Comment by shaohuzhang1** [comment]
vscode idea 对java支持不是很友善,我们一般使用IntelliJ IDEA 进行开发.你可以使用IntelliJ IDEA 试一下
