### ISSUE TITLE
[BUG][云主机管理][Proxmox][云主机]创建云主机，当模板系统盘以MB为单位时，计费单位未转换，计费错误

### ISSUE THREAD

**Issue by yezifengHZ** [CloudExplorer-Dev/CloudExplorer-Lite#266]
### CloudExplorer Lite 版本

v1.4.1

### 问题描述

创建云主机，当模板系统盘以MB为单位时，计费单位未转换，计费错误

![image](https://github.com/CloudExplorer-Dev/CloudExplorer-Lite/assets/75710266/2fd4491d-8b78-46ae-872e-96b9ae373983)

### 重现步骤

根据Proxmox文档部署cloudinit模板虚拟机：[https://pve.proxmox.com/wiki/Cloud-Init_Support](url)

通过ubuntu cloudinit img映像导入磁盘得到以MB为单位的系统盘
```
qm disk import <vmid> <source> <storage> [OPTIONS]
```

然后在CloudExplorer Lite管理平台选择该模板创建云主机，得到错误的花费计算

![image](https://github.com/CloudExplorer-Dev/CloudExplorer-Lite/assets/75710266/a7f9b507-fb9e-428c-a12b-eb1966e1d43b)

**Comment by shaohuzhang1** [comment]
感谢反馈,确认这是一个bug,等待排期修复
