### ISSUE TITLE
[feature][云主机]vmware][云主机]云主机无法自定义

### ISSUE THREAD

**Issue by shadowwalker-xu** [CloudExplorer-Dev/CloudExplorer-Lite#268]
### CloudExplorer Lite 版本

1.4.1

### 请描述您的需求或者改进建议

在vmware新建云主机时，系统盘无法修改大小，包括无法新增设备，比如新增的pci设备，配置显卡直通等

**Comment by baixin513** [comment]
感谢您的反馈。回答如下：
1、当前创建 VMware 云主机是通过克隆镜像的方式创建的，系统盘大小与镜像一致无法修改，但可以新增数据盘。
2、不支持新增的pci设备，配置显卡直通等功能。
