### ISSUE TITLE
[BUG][模块名称][云厂商][功能菜单]缺陷描述

### ISSUE THREAD

**Issue by KKISO574** [CloudExplorer-Dev/CloudExplorer-Lite#269]
### 联系方式

2911074976@qq.com

### CloudExplorer Lite 版本

v1.4.1

### 问题描述

使用pve模版创建好后，机器开机了，任务还一直卡在创建中，手动点击同步会出来一个新的机器，但是之前那个任务还在一直进行。手动把机器删除在同步也没法让任务超时。
在阿里云平台上创建ecs后且没法直接开机，显示任务失败，阿里云平台上机器状态是停止，需要我手动同步

### 重现步骤

阿里云正常操作开机，他创建完成后是停止状态，平台显示timeout
pve是采用模板启动，可能是镜像没有安装qemu-guest-agent
![微信截图_20231229154707](https://github.com/CloudExplorer-Dev/CloudExplorer-Lite/assets/68904107/32f25a17-4277-4ba0-a42c-d34eb609eb84)

### 期待的正确结果

希望能在创建或者开关机时候，点击这个模块，能对这个步骤进行一个超时提醒，单独对这个功能区同步他的状态，

**Comment by baixin513** [comment]
您好，云管会定时同步纳管的云账号下的资源，也可以手动同步云账号下资源，无法实时同步资源，这样会很耗资源，展示数据也很慢，建议您能使用云管操作就不要经常到其他云平台上操作。
