### ISSUE TITLE
创建VMware虚拟机时支持选择预设实例规格

### ISSUE THREAD

**Issue by xiaoluyahei** [CloudExplorer-Dev/CloudExplorer-Lite#27]
### CloudExplorer Lite 版本

V1.0.0

### 请描述您的需求或者改进建议

![image](https://user-images.githubusercontent.com/131225593/233027942-cbef63c4-b993-4eba-9721-922be8314202.png)

每次创建新的虚拟机都需要选择各种规格，能否支持自定义一个预设的规格，省去前面重复的操作

**Comment by baixin513** [comment]
感谢反馈，我们先内部讨论一下。有结论，这里回复。

**Comment by xiaoluyahei** [comment]
ok

**Comment by baixin513** [comment]
结论：1、增加实例规格配置功能。
           2、创建VMware 云主机 实例规格可以选择已有实例规格或新增实例规格。

**Comment by bigbird1985** [comment]
非常有需求，可以节省很多时间。

**Comment by baixin513** [comment]
经过内部讨论后，认为加入实例规格意义应该是为了限制某些用户只能创建某些实例规格的资源，应该与组织/工作空间绑定，若当前仅在创建实例时把输入的配置换成选择实例规格，还要提前配置一下规格并没有多方便。所以近期先不安排该issue了。

**Comment by ardenboy** [comment]
一般使用的都是常用的实例规格，每次点击调整参数是有点麻烦，包括配置的网卡（一般默认即可），如公有云的规格就比较方便，包括计费也是直接根据实例规格来，该功能期待后期能增加。

**Comment by ardenboy** [comment]
一般使用的都是常用的实例规格，私有云创建时每次点击调整参数是有点麻烦，包括配置的网卡（一般默认即可），如公有云的规格就比较方便，包括计费也是直接根据实例规格来，期待后期能增加。
