### ISSUE TITLE
[FEATURE][费用分析][阿里云华为云][费用变更] 展示某一个月费用的变更情况

### ISSUE THREAD

**Issue by 106848748** [CloudExplorer-Dev/CloudExplorer-Lite#270]
### CloudExplorer Lite 版本

还没装

### 请描述您的需求或者改进建议

详细展示某一个资产这个月的费用变化情况，为什么增加、减少了费用。

### 请描述你建议的实现方案

我现在实现的方案是，账号名称+实例id+计费项作为一个唯一标识，与上个月进行对比，得出：增加、减少、无变化

**Comment by 106848748** [comment]
分析每个月的时候，还没分析下上个月，让上个月感知到某一个资产费用减少是降配，还是资源回收

**Comment by 106848748** [comment]
费用增加：配置增加、新购

**Comment by 106848748** [comment]
费用减少：配置降配、释放

**Comment by 106848748** [comment]
分析上个月的时候：

**Comment by 106848748** [comment]
分析上个月的时候：
# 因为上个月释放的实例，在本月需要体现费用减少
# 上个月释放，有退款，但没有续费，所以上个月的费用是负数，到本月体现就是正数（增加费用）
# 上个月释放，有续费，则一定使用费用，到本月体现就是负数（减少费用）
添加一个假账单来体现

**Comment by 106848748** [comment]
做出来的效果是感知到哪些资产的费用增加了，根据计费项知道是为什么增加，哪些资产的费用降低了，是降配还是回收

**Comment by 106848748** [comment]
看现在的费用功能都是根据一些字段来统计，这些是用作汇报的，真实的肯定是需要感知资产的费用变化情况

**Comment by 106848748** [comment]
每个月都有写备注，记录这个月费用的整体变化情况

**Comment by shaohuzhang1** [comment]
自定义账单使用资源名称进行统计,就可以分析除某一个资源在未来6个月的账单趋势,不知道是否可用解决你的问题
![image](https://github.com/CloudExplorer-Dev/CloudExplorer-Lite/assets/80892890/e28d4f08-d9ad-4820-a634-fae22c6c116d)
![image](https://github.com/CloudExplorer-Dev/CloudExplorer-Lite/assets/80892890/ccc31eba-c632-4787-89e3-3ad507c12318)
