### ISSUE TITLE
建议增加aws公有云支持

### ISSUE THREAD

**Issue by grandwill** [CloudExplorer-Dev/CloudExplorer-Lite#272]
### CloudExplorer Lite 版本

1.4

### 请描述您的需求或者改进建议

希望能支持aws 的云机器管理

**Comment by baixin513** [comment]
感谢您的反馈，当前开源版还不支持 AWS，您可以了解下我们的商业版，不仅支持 AWS 还有更强大的功能。https://fit2cloud.com/cmp/index.html
