### ISSUE TITLE
[FEATURE][模块名称][云厂商][功能菜单]需求描述

### ISSUE THREAD

**Issue by sjditadmin** [CloudExplorer-Dev/CloudExplorer-Lite#273]
### CloudExplorer Lite 版本

v1.4.1

### 请描述您的需求或者改进建议

![image](https://github.com/CloudExplorer-Dev/CloudExplorer-Lite/assets/20395848/585cf525-7ffc-4459-b24d-7f0616f3fdf3)
云主机分析的资源明细里面的取值范围是多少，能否自定义取值范围，比如7天，30天的平均值

**Comment by baixin513** [comment]
资源明细中监控数据时获取的实时数据。
