### ISSUE TITLE
离线安装问题

### ISSUE THREAD

**Issue by finovy** [CloudExplorer-Dev/CloudExplorer-Lite#274]
### 请描述您的问题

我按照官方文档的离线安装实例执行了安装过程，但是服务一直起不来，报错如下：

主应用:
x gateway pid: status:unhealthy x
x eureka pid:9 status:healthy x
x management-center pid:10 status:unhealthy x
其他模块:
x operation-analysis pid: status:unhealthy x
x vm-service pid: status:unhealthy x
x finance-management pid: status:unhealthy x
x security-compliance pid: status:unhealthy x

![图片](https://github.com/CloudExplorer-Dev/CloudExplorer-Lite/assets/139359420/41f4b0ee-e93e-4052-a577-ba9fbb01901e)

**Comment by baixin513** [comment]
一半是 MySQL 未启动，或者服务器内存资源不足导致的，可以排查一下原因。
