### ISSUE TITLE
[FEATURE][云主机][vmware｜openstack｜proxmox][创建云主机]增加云主机到期时间

### ISSUE THREAD

**Issue by airsmon** [CloudExplorer-Dev/CloudExplorer-Lite#276]
### CloudExplorer Lite 版本

v1.4.1

### 请描述您的需求或者改进建议

1，对私有云上的VM增加一个生命周期（到期自动shutdown或释放）

**Comment by baixin513** [comment]
你好，开源版暂不支持，企业版支持该功能，可以试用一下。
