### ISSUE TITLE
[FEATURE][模块名称][云厂商][功能菜单]是否可以新增对于“轻量应用服务器”的纳管

### ISSUE THREAD

**Issue by bluesky4485** [CloudExplorer-Dev/CloudExplorer-Lite#277]
### CloudExplorer Lite 版本

v1.4.1

### 请描述您的需求或者改进建议

阿里云和腾讯云除了ecs云服务器之外，还有轻量应用服务器，貌似现在同步云资源过来的信息 不包括 轻量应用服务器，只有云服务器，是否可以将 轻量应用服务器 也接入过来，一起管理？

### 请描述你建议的实现方案

建议 我的资源 中加入 轻量应用服务器 这类资源

**Comment by baixin513** [comment]
感谢反馈，暂无计划。
