### ISSUE TITLE
运营分析-显示样式优化

### ISSUE THREAD

**Issue by liuxinxin2020** [CloudExplorer-Dev/CloudExplorer-Lite#28]
### CloudExplorer Lite 版本

v1.0.0

### 请描述您的需求或者改进建议

运营分析-显示样式优化
CPU使用率、内存使用率：建议显示统一的小数点保留位数、建议统一右对齐。

**Comment by baixin513** [comment]
该问题已在V1.0.2中解决，欢迎使用。

**Comment by liuxinxin2020** [comment]
保留的小数点位数依然不统一
<img width="1476" alt="image" src="https://github.com/CloudExplorer-Dev/CloudExplorer-Lite/assets/72063838/434443dc-9dae-4ecf-a8ee-835cf5e82e46">
