### ISSUE TITLE
[FEATURE] 希望增加一个云dns管理的功能

### ISSUE THREAD

**Issue by 0x5c0f** [CloudExplorer-Dev/CloudExplorer-Lite#284]
### CloudExplorer Lite 版本

v1.4.1

### 请描述您的需求或者改进建议

希望能增加一个云dns管理的功能， 一般来说每个帐号都可能会注册域名，这样，如果没有统一的dns管理，在解析dns的时候就需要登陆到具体帐号上去操作，这个功能感觉还是挺不错的，希望能在 `cloudexplorer`上实现。

### 请描述你建议的实现方案

无

**Comment by baixin513** [comment]
感谢反馈，商业版支持，如有需要可以联系商务试用。

**Comment by 0x5c0f** [comment]
🤣
