### ISSUE TITLE
有物理机的管理功能吗？

### ISSUE THREAD

**Issue by shuoshadow** [CloudExplorer-Dev/CloudExplorer-Lite#3]
刚开源吗？有管理物理机的功能吗？比如添加物理机后，使用物理机创建出虚拟机

**Comment by baixin513** [comment]
是的，感谢您的反馈，关于物理机管理近期还先不考虑的。如有需要可以关注我们的物理机项目rackshift。
代码仓库：https://github.com/fit2cloud/rackshift
