### ISSUE TITLE
VMware虚拟机支持CPU/内存热插拔设置，配置变更时可无需关机

### ISSUE THREAD

**Issue by xiaoluyahei** [CloudExplorer-Dev/CloudExplorer-Lite#30]
### CloudExplorer Lite 版本

V1.0.0

### 请描述您的需求或者改进建议

![image](https://user-images.githubusercontent.com/131225593/233034624-c086b983-4dce-42f2-a4a0-e8f9dbc1d334.png)
![image](https://user-images.githubusercontent.com/131225593/233034919-663988b7-27aa-46eb-9db7-efa7b8906afb.png)

VMWare支持内存、CPU的热添加，不需要关闭虚拟机就可以实现配置的修改。但减配只能在关机状态下进行。如果是增加配置，则不需要关机，能否做个选项，因为有些业务不能随意关机重启

**Comment by baixin513** [comment]
感谢反馈！
1、当前云管同步VMware虚拟机资源时未同步资源的CPU和内存的热插拔属性，我们需要调研一些VMware是否有相应的接口。
2、VMware上CPU和内存的热插拔是分开设置，且只有关机情况才能设置开启，不同机器可能也设置的不一样。如果做该功能，应该是在云主机列表的操作列，增加CPU/内存热插拔设置功能。都是开启状态在配置变更时不在关机。否则还是要关机。

3、配置变更这种操作都会比较谨慎，一般应该会选择在业务停机维护窗口期进行操作。变更的频率也是非常少。

我们近期先没规划这个功能，后面如果用户需求比较强烈了我们再进行规划。

**Comment by xiaoluyahei** [comment]
ok
