### ISSUE TITLE
【运营分析】-云主机优化中可设置优化资源的范围增加排除资源

### ISSUE THREAD

**Issue by xiaoluyahei** [CloudExplorer-Dev/CloudExplorer-Lite#33]
### CloudExplorer Lite 版本

V1.0.0

### 请描述您的需求或者改进建议

![c621500def0a0612a7041574439a5cc](https://user-images.githubusercontent.com/131225593/233235702-72369f5d-653b-483d-90cf-3def33611d11.png)
![801b68b4c67bc64ff1ed350d6e3181e](https://user-images.githubusercontent.com/131225593/233235720-17a247df-5ca3-4319-a594-0e96824068f3.png)
图一云主机优化这块，有的主机我是否能忽略  这样就可以排除在外了，因为有些主机是特定条件存在的，所以资源大小就不管了
还有就是图二这两个地方 是否增加筛选条件 比如根据我的网段 或者名称模糊匹配、模糊排除（模糊匹配反选），这样便于快速筛选机器

**Comment by baixin513** [comment]
感谢反馈，您的建议将会被采纳。实现方案考虑如下：
一、资源优化中增加排除资源，考虑在2个地方实现：
      1、 在制定每个优化策略时，会让用户选择优化资源范围：优化资源列表和排除资源列表（按资源，按组织/工作空间 选择排除资源）。
      2、在需要优化的资源列表后，增加操作列，可选择忽略某个资源，列表下方增加 排除忽略功能，被排除的资源日后将不再参与优化策略。
      3、如果想要排除资源再次加入到优化资源范围，需要到每个资源优化策略中把排除资源移除。
二、资源优化列表右上角搜索条件字段增加按IP地址模糊查询。
三、当前已支持名称模块查询。（不做修改）

**Comment by xiaoluyahei** [comment]
![image](https://user-images.githubusercontent.com/131225593/233288369-b8f8cd35-a334-46a8-8832-57a667daf194.png)
另外想反馈一个问题是，企业中办公使用的云桌面会存在，每天下班之后，无人使用的情况下会自动关机，直到第二天上班时才会被打开，那针对这种情况，资源的平均使用率还会准确嘛？这方面会考虑优化吗？

**Comment by baixin513** [comment]
1、如果云主机关机的话是采集不到监控数据的，不会插入监控记录的，可以查看监控图中没有数据点位。

2、计算方式：平均使用率 = 采集到的使用率总和/ 所有采集到监控数据记录数。

**Comment by xiaoluyahei** [comment]
收到

**Comment by baixin513** [comment]
该功能在v1.2.0版本中实现，欢迎试用。
