### ISSUE TITLE
云主机在关机状态时监控图的样式连接线断开显示优化

### ISSUE THREAD

**Issue by xiaoluyahei** [CloudExplorer-Dev/CloudExplorer-Lite#34]
### CloudExplorer Lite 版本

V1.0.0

### 请描述您的需求或者改进建议

![9d0e52af3971fa1a61a6eed867404a9](https://user-images.githubusercontent.com/131225593/233236109-4d5d54fe-ab14-480d-9ab5-a53079a15cff.png)
![737d9a397ea552a33635aaba7ab1781](https://user-images.githubusercontent.com/131225593/233236117-d5ee5530-48e0-4196-b3ec-00be829fbf50.png)
这段时间内 虚拟机时关机的 ，所以CPU是0  ce平台上这个样式能否修改优化一下 。一个长坡，  第一眼以为是cpu在增长。
能否改成和VC一个样式的，关机就断开，这样一眼就知道某一时间段，云主机是处于一个什么样的状态，资源使用变化情况，一目了然。

**Comment by baixin513** [comment]
感谢反馈，您的建议已采纳，请关注后续版本。

**Comment by xiaoluyahei** [comment]
ok

**Comment by baixin513** [comment]
您好，我们在解决资源关机情况未获取连线断开显示时，发现部分云平台返回的数据断点较多，若采用连线断开的现实方式，监控图显示影响较大。我们需要再做进一步的排查及处理。故我们暂时先把该优化放到后面版本进行一次性解决。

**Comment by baixin513** [comment]
该issue已在v1.1.0中解决
