### ISSUE TITLE
[BUG]费用趋势页面金额显示异常

### ISSUE THREAD

**Issue by yuqun-nj** [CloudExplorer-Dev/CloudExplorer-Lite#35]
### 联系方式

qun.yu@fit2cloud.com

### CloudExplorer Lite 版本

v1.0.0

### 问题描述

![image](https://user-images.githubusercontent.com/97491875/233240026-4af101fa-78ac-4b37-a49d-c647e4b64f32.png)

### 重现步骤

云账单模块-账单总览页面底部费用明显，费用趋势大图显示金额NaN

**Comment by Shenguobin0102** [comment]
感谢反馈，已确认并规划解决，请关注后续版本。

**Comment by baixin513** [comment]
该问题已在V1.0.1中已解决，版本已发布欢迎试用。
