### ISSUE TITLE
关于监控数据-希望可以设置清空策略

### ISSUE THREAD

**Issue by liuxinxin2020** [CloudExplorer-Dev/CloudExplorer-Lite#39]
### CloudExplorer Lite 版本

v1.0.0

### 请描述您的需求或者改进建议

现状：目前关于资源的监控数据是永久保留，不进行清空。
问题：时间久了，可能会把数据库撑爆；
建议：类似系统日志，可以设置监控数据清空策略，设置监控数据包括时长。

**Comment by baixin513** [comment]
感谢反馈，这块我们需要内部讨论一下。
