### ISSUE TITLE
[BUG]分账规则云账号名称与管理中心不一致

### ISSUE THREAD

**Issue by yuqun-nj** [CloudExplorer-Dev/CloudExplorer-Lite#41]
### 联系方式

qun.yu@fit2cloud.com

### CloudExplorer Lite 版本

v1.0.0

### 问题描述

![image](https://user-images.githubusercontent.com/97491875/233244811-ae89772c-ef60-4aad-8f53-d019aae4db0c.png)
![image](https://user-images.githubusercontent.com/97491875/233244836-1abed0d2-aea1-49bd-aa1b-44dae74f1ae7.png)
修改云账号名称并重新同步后分账规则页面云账号未同步修改

### 重现步骤

1、修改管理中心云账号名称并完成同步
2、点击云账单模块-分账设置，选中一个组织添加分账规则选择云账号，发现可选云账号与管理中心名称不一致

**Comment by Shenguobin0102** [comment]
感谢反馈，已确认问题，会在后续版本中规划修复，请关注后续版本。
