### ISSUE TITLE
[FEATURE]鼠标悬停[组织结构分布]区域页面无法滑动

### ISSUE THREAD

**Issue by yuqun-nj** [CloudExplorer-Dev/CloudExplorer-Lite#42]
### CloudExplorer Lite 版本

v1.0.0

### 请描述您的需求或者改进建议

![image](https://user-images.githubusercontent.com/97491875/233246107-ba78cc49-b006-4cda-b0fc-8cf7a841803f.png)
1、运营分析总览页面-组织架构分布
2、运营分析-资源分析-磁盘分析-组织架构分布
鼠标悬停在该区域，并选中柱状图数据后发现页面无法正常滑动，移动鼠标至其他区域页面滑动功能正常

**Comment by baixin513** [comment]
感谢反馈，不能滚动页面的原因是该组件含有内部滚动条。
鼠标在此组件滚动仅对当前组织有效，若想滚动页面，需将鼠标放在有滚动条的组件外部再滚动。

不过在组件没有呈现滚动条的时候，可滚动整页面优化一下。
