### ISSUE TITLE
希望可以设置自定义账单在账单总览页面中的显示顺序

### ISSUE THREAD

**Issue by liuxinxin2020** [CloudExplorer-Dev/CloudExplorer-Lite#44]
### CloudExplorer Lite 版本

v1.0.0

### 请描述您的需求或者改进建议

现状：自定义账单在账单总览页面中的显示顺序随机、不可控。
希望：在自定义账单中可以设置账单在总览账单中的显示顺序。

**Comment by liuxinxin2020** [comment]
如果没有排序，无法将关注的账单显示在最前面，甚至会是一些临时测试的自定义账单显示在了最前面。

**Comment by baixin513** [comment]
如果账单数据较多时会显示，在更多里面选择的账单会自动显示在第一个位置。想让哪个放前面，可以在更多里面选择菜单。
 后期会考虑一下支持排序功能。

**Comment by baixin513** [comment]
感谢反馈，经过讨论该需求近期内无法支持，该ISSUE将会关闭。
