### ISSUE TITLE
[FEATURE]在云主机页面对某台云主机进行添加磁盘的操作，点击保存后，页面停留在云主机页面，没有任何提示，不知道磁盘是否添加成功。

### ISSUE THREAD

**Issue by supersarah123** [CloudExplorer-Dev/CloudExplorer-Lite#46]
### CloudExplorer Lite 版本

v1.0.0

### 请描述您的需求或者改进建议

在云主机页面对某台云主机进行添加磁盘的操作，点击保存后，页面停留在云主机页面，没有任何提示，不知道磁盘是否添加成功。

### 请描述你建议的实现方案

建议添加磁盘后页面给出添加成功或者失败弹出框

**Comment by baixin513** [comment]
给云主机添加磁盘 提交后会生成一条添加磁盘的任务，任务中有相关的任务进度和状态。
如果执行失败在任务状态是失败，打开任务详情可以看到失败的原因。
由于该类型的任务是异步执行，弹出提示不太合适。

后期规划增加消息通知功能时，在消息通知中进行通知。请关注后续版本。
