### ISSUE TITLE
[FEATURE]所有页面的列表没有了刷新按钮，列表的刷新只能通过刷新浏览器，操作不方便。

### ISSUE THREAD

**Issue by supersarah123** [CloudExplorer-Dev/CloudExplorer-Lite#47]
### CloudExplorer Lite 版本

v1.0.0

### 请描述您的需求或者改进建议

所有页面的列表没有了刷新按钮，列表的刷新只能通过刷新浏览器，操作不方便。

**Comment by liuxinxin2020** [comment]
同样期待增加列表的刷新功能。

**Comment by baixin513** [comment]
该功能在v1.2.0版本实现，欢迎使用。
