### ISSUE TITLE
[FEATURE]磁盘列表中vmware类型的磁盘不能卸载、删除，希望能支持。

### ISSUE THREAD

**Issue by supersarah123** [CloudExplorer-Dev/CloudExplorer-Lite#48]
### CloudExplorer Lite 版本

v1.0.0

### 请描述您的需求或者改进建议

磁盘列表中vmware类型的磁盘不能卸载、删除，希望能支持。

**Comment by baixin513** [comment]
您好，VMware 的磁盘卸载/挂载处理上相对公有云来说是非常复杂的。
 VMware磁盘删除有2种方式，1、删除数据文件（云管的磁盘删除操作）2  虚拟机中移除（可理解为为实现的磁盘卸载功能）。

当前云管的磁盘资源是通过虚拟机的维度关联的。如果在虚拟机中移除（卸载）磁盘，云管是无法遍历到这块磁盘的。
需要到存储文件中逐个遍历每个文件夹中再次反查是否有未关联的vmdk文件，当用户的资源数量较多时，这个遍历操作非常耗时。
故综合考虑后，暂未支持VMware磁盘卸载/挂载功能。

其他用户如有需求，或更好的实现方案可以追加在后面。
