### ISSUE TITLE
切换角色后默认定位到当前页面

### ISSUE THREAD

**Issue by liuxinxin2020** [CloudExplorer-Dev/CloudExplorer-Lite#5]
### CloudExplorer Lite 版本

v1.0.0

### 请描述您的需求或者改进建议

现状：切换角色后统一跳转到首页，使用不方便

### 请描述你建议的实现方案

期望：切换角色后默认定位到当前页面

**Comment by baixin513** [comment]
感谢反馈，我们会在后续版本优化

**Comment by baixin513** [comment]
该Issue已在V1.0.1版本中优化，版本已发布欢迎试用。
