### ISSUE TITLE
[FEATURE]创建阿里云云主机时可设置磁盘的随实例删除属性

### ISSUE THREAD

**Issue by supersarah123** [CloudExplorer-Dev/CloudExplorer-Lite#50]
### CloudExplorer Lite 版本

v1.0.0

### 请描述您的需求或者改进建议

创建阿里云云主机，磁盘默认只能随实例删除，且为灰色，不能选择,但是单独创建磁盘，就可以选择

### 请描述你建议的实现方案

希望在创建阿里云的云主机时，磁盘可以不够选随实例删除

**Comment by baixin513** [comment]
感谢反馈，阿里云厂商在创建云主机时添加磁盘的API 接口中未提供 该属性，故不支持在创建云主机时设置磁盘的【随实例删除 】属性。后续版本我们会隐藏不支持的属性。
