### ISSUE TITLE
[FEATURE]创建vmware云主机时，如果参数填写不全，往上翻才知道哪里没填

### ISSUE THREAD

**Issue by supersarah123** [CloudExplorer-Dev/CloudExplorer-Lite#51]
### CloudExplorer Lite 版本

v1.0.0

### 请描述您的需求或者改进建议

希望可以明显指示出缺少什么参数

**Comment by baixin513** [comment]
我们在V1.1.0版本中对创建云主机的表单页面进行了优化，请关注下v1.1.0版本。
