### ISSUE TITLE
公有云云主机-针对包年包月的云主机增加续期功能，支持变更付费方式功能

### ISSUE THREAD

**Issue by liuxinxin2020** [CloudExplorer-Dev/CloudExplorer-Lite#52]
### CloudExplorer Lite 版本

v1.0.0

### 请描述您的需求或者改进建议

希望支持如下功能：
1、按需、包周期资源类型互相转换；
2、包周期资源支持续期。

**Comment by baixin513** [comment]
该需求的续期功能已在v1.4.0版本中实现，请升级试用。该issue将会关闭，如有其他需求请重新提交issue。
