### ISSUE TITLE
[BUG]添加磁盘的输入参数的步长、异常数据处理需优化

### ISSUE THREAD

**Issue by supersarah123** [CloudExplorer-Dev/CloudExplorer-Lite#53]
### CloudExplorer Lite 版本

v1.0.0

### 问题描述

添加磁盘时磁盘大小的数字没有做限制，可以随意输入，甚至是负数

### 重现步骤

<img width="935" alt="image" src="https://user-images.githubusercontent.com/45278450/233254601-595266d9-2868-4d40-af19-42cd95b11c88.png">

**Comment by Shenguobin0102** [comment]
非法输入（比如负数、小于10的数字）会在输入框失去光标后自动重置为10，即使输入框获得光标的情况下直接提交任务，也会重置参数为合法参数。这里会做一些优化，比如将负数和小数的输入直接禁止，请关注后续版本。

**Comment by baixin513** [comment]
该问题已在v1.1.0版本中解决。
