### ISSUE TITLE
[BUG]vmware申请云主机磁盘的参数和添加磁盘时参数的选择不一样

### ISSUE THREAD

**Issue by supersarah123** [CloudExplorer-Dev/CloudExplorer-Lite#54]
### CloudExplorer Lite 版本

v1.0.0

### 问题描述

vmware申请云主机磁盘的参数和添加磁盘时参数的选择不一样

### 重现步骤

<img width="846" alt="image" src="https://user-images.githubusercontent.com/45278450/233255089-3bdb9dc8-d136-48b6-bf33-87f1292263b2.png">

<img width="935" alt="image" src="https://user-images.githubusercontent.com/45278450/233254844-2482ec2e-75f6-4c63-9d1a-e2f50c41fb26.png">

**Comment by Shenguobin0102** [comment]
CloudExplorer Lite 创建 VMware 虚拟机的是通过克隆模板的方式进行的，在 vCenter 上通过克隆模板创建虚拟机，也是不能设置磁盘的模式和存储目录的，而创建磁盘的时候，这些参数都是可以设置的，所以我们和 vCenter 保持了一致。
