### ISSUE TITLE
[BUG]磁盘列表中vmware的磁盘没有区分系统盘、磁盘属性全为数据盘

### ISSUE THREAD

**Issue by supersarah123** [CloudExplorer-Dev/CloudExplorer-Lite#55]
### CloudExplorer Lite 版本

v1.0.0

### 问题描述

磁盘列表中vmware的磁盘没有区分系统盘、磁盘属性全为数据盘

### 重现步骤

<img width="882" alt="image" src="https://user-images.githubusercontent.com/45278450/233255900-4ab2c72c-cd18-49b4-a7e1-4422a56d5886.png">

<img width="1070" alt="image" src="https://user-images.githubusercontent.com/45278450/233255804-11100b54-08a7-4e9e-a135-f75c9d9ad373.png">

**Comment by Shenguobin0102** [comment]
感谢反馈。这个问题目前无法修复， VMware 的接口返回数据中没有提供是否是启动盘的标记，VMware 中没有系统盘或者启动盘这个概念；如果按照磁盘名称，直接将名称为“硬盘1”的磁盘标记为启动盘，也会存在问题。所以，暂时保持现状。
