### ISSUE TITLE
【云主机管理】-对云主机管理操作增加网卡的配置变更

### ISSUE THREAD

**Issue by xiaoluyahei** [CloudExplorer-Dev/CloudExplorer-Lite#60]
### CloudExplorer Lite 版本

V1.0.0

### 请描述您的需求或者改进建议

![image](https://user-images.githubusercontent.com/131225593/233277509-92a32ea3-d39b-4588-9dbf-07f8566caf05.png)
目前只有对CPU和内存的配置变更，能否支持对虚拟机网卡的配置变更（例如：网卡增删、网卡改变）

**Comment by baixin513** [comment]
想了解下使用情况：
1、在什么情况下会变更网卡呢？ 
2、该操作出现的频率有多高呢？

**Comment by xiaoluyahei** [comment]
这个 情况，一般是用户根据业务需求提出配置变更，频率不是特别高
