### ISSUE TITLE
API需求描述

### ISSUE THREAD

**Issue by wjl2757** [CloudExplorer-Dev/CloudExplorer-Lite#64]
### CloudExplorer Lite 版本

V1.0.1

### 请描述您的需求或者改进建议

建议增加该版本的对外API，API是云管纳管云平台资源的便捷手段，在使用便捷的同时，也应具备全量级的云管API

### 请描述你建议的实现方案

开放业务调用API，尽量复用前端调用的API

**Comment by baixin513** [comment]
感谢反馈，API开放我们需要整体的整理一下，该功能会在v1.2.0版本中支持，还请关注下后续版本。

**Comment by baixin513** [comment]
该功能在V1.2.0版本实现，欢迎使用。
