### ISSUE TITLE
删除云账号后，安全合规中的数据没有同步清理掉

### ISSUE THREAD

**Issue by liuxinxin2020** [CloudExplorer-Dev/CloudExplorer-Lite#65]
### CloudExplorer Lite 版本

v1.0.0

### 问题描述

删除云账号后，安全合规模块总览页面和扫描检查页面的数据没有同步清理掉。

### 重现步骤

1、删除云账号
2、查看安全规格总览页面
3、查看安全合规扫描检查页面

**Comment by Shenguobin0102** [comment]
安全合规的扫描使用的云资源数据是存储在 ES 中的，不能随着云账号的删除实时删除；云账号删除后，会在下一次安全合规执行定时扫描任务时将不存在的云账号的数据全部删除，所以需要等待下一次定时扫描任务执行后再去查看。

**Comment by liuxinxin2020** [comment]
希望可以随着删除云账号直接删除；如果不能直接删除，页面上进行控制，不显示已经删除的云账号的扫描结果也可以；
不然，如果删除某个云账号，直接去看当前扫描的结果，页面中会存在冗余的数据。

**Comment by baixin513** [comment]
该issue在v1.1.0版本中已解决。

**Comment by liuxinxin2020** [comment]
v1.1.0版本中，删除云账号后，安全合规中的数据依然没有清理掉。
