### ISSUE TITLE
[FEATURE][运营分析][VC][资源分析-基础资源分析]-希望增加上宿主机相关cpu使用率、内存使用率

### ISSUE THREAD

**Issue by lixuejun725** [CloudExplorer-Dev/CloudExplorer-Lite#68]
### CloudExplorer Lite 版本

1.0

### 请描述您的需求或者改进建议

由于VC部分宿主机无法申请资源，登录云管平台，无法查看相关宿主机使用情况，显示的CPU使用情况是核数，和分配情况，无法准确判断资源使用真实情况，希望能够加上相关资源使用率，数据或者趋势图都挺好的
当前云平台现状：
![image](https://user-images.githubusercontent.com/38548829/233597891-1964b4cc-8bc3-4bda-8530-ec220888bc4c.png)
期望结果：
![image](https://user-images.githubusercontent.com/38548829/233597892-f50a2d7d-d77d-437b-99aa-773b3bc8bc5e.png)
<img width="1226" alt="image" src="https://user-images.githubusercontent.com/38548829/233598228-23a96b4f-9c61-45a7-bf12-27c6f6422f31.png">

**Comment by baixin513** [comment]
感谢反馈，该功能已实现前端未展现出来，请关注v1.0.2版本。

**Comment by learnzpk** [comment]
![image](https://user-images.githubusercontent.com/30232608/234727286-76d1a3a1-b3f3-4143-b8c6-38474dfee047.png)
1.0.2版本添加内容后存在浮点数精度丢失问题，建议保留两位小数

**Comment by baixin513** [comment]
感谢反馈，该问题已在v1.0.2版本中解决。欢迎更新使用。
