### ISSUE TITLE
[FEATURE]针对宿主机支持监控告警功能，根据预设的告警规则、告警等级、通知方式，进行对应的告警通知提示用户进行处理

### ISSUE THREAD

**Issue by lixuejun725** [CloudExplorer-Dev/CloudExplorer-Lite#69]
### CloudExplorer Lite 版本

1.0

### 请描述您的需求或者改进建议

现象：当前云管平台似乎包含了优化建议，但是缺少用户直观提示，最近宿主机出现资源不足，用户无法正常申请资源，期望能够在相关资源使用到一定阈值的时候提示相关用户去处理平台资源。
期望结果：
![image](https://user-images.githubusercontent.com/38548829/233600032-2cfc237e-2fb6-473b-abae-b5dbe1a53d07.png)

**Comment by baixin513** [comment]
您指的应该是监控告警功能，根据预设的告警规则、告警等级、通知方式，进行对应的告警通知吧。

**Comment by lixuejun725** [comment]
是的

**Comment by baixin513** [comment]
感谢反馈，经过讨论该需求近期内无法支持，如有需要可以了解下商业版云管，该ISSUE将会关闭。
