### ISSUE TITLE
[FEATURE][云主机管理][文档] 新增对其他平台支持

### ISSUE THREAD

**Issue by hackmeta** [CloudExplorer-Dev/CloudExplorer-Lite#71]
### CloudExplorer Lite 版本

v1

### 请描述您的需求或者改进建议

我们有很多其他云平台和虚拟化的环境，需要《新增对其他平台支持的开发文档》，以便我们能够支持更多的云平台产品、超融合产品、容器产品等，可以扩大用户数量。

**Comment by baixin513** [comment]
感谢关注和支持，我们正在梳理扩展云平台的这块的代码和结构。待完善后会更新在线文档并在该issue通知您，请关注下后续通知。

**Comment by baixin513** [comment]
感谢反馈，近期内无法支持，该ISSUE将会关闭。
