### ISSUE TITLE
模块构建不成功

### ISSUE THREAD

**Issue by Ryze-T** [CloudExplorer-Dev/CloudExplorer-Lite#72]
### 请描述您的问题

Non-resolvable parent POM for com.fit2cloud:demo:${revision}: Could not find artifact com.fit2cloud:cloudexplorer-lite:pom:${revision}

**Comment by ulleo** [comment]
你可以在项目根目录执行：
./mvnw install

**Comment by Ryze-T** [comment]
上传模块需要上传 .tar.gz，这个压缩包怎么构成？我应该打包什么这些都没说

**Comment by ulleo** [comment]
你可以查看文档，里面有简单案例：
https://fit2cloud.com/cloudexplorer-lite/docs/best_practices/
我们也发现现在的模块包还不能支持所有的开发情况，这块我们还打算调整优化一下。

同时我们的开发部署文档也还在优化调整中，你可以关注我们的文档改动。
