### ISSUE TITLE
[FEATURE]建议增加docker、docker-compose、k8s的部署方式

### ISSUE THREAD

**Issue by macaty** [CloudExplorer-Dev/CloudExplorer-Lite#75]
### CloudExplorer Lite 版本

1.0.1

### 请描述您的需求或者改进建议

]建议增加docker、docker-compose、k8s的部署方式

### 请描述你建议的实现方案

]建议增加docker、docker-compose、k8s的部署方式

**Comment by ulleo** [comment]
我们当前发布的安装包部署方式就是使用了 docker-compose，你可以根据安装包中的 docker-compose 文件调整为 docker 或者 k8s 的部署方式
