### ISSUE TITLE
[云账号]支持pve及ovirt虚拟化平台 有需求的用户可以在此追加需求

### ISSUE THREAD

**Issue by lucashaha** [CloudExplorer-Dev/CloudExplorer-Lite#79]
### CloudExplorer Lite 版本

1.0.1

### 请描述您的需求或者改进建议

云管平台能否支持pve和ovirt虚拟机，私有云openstack太重，proxmox virtual environment和ovirt在EDA等领域用的比openstack多，毕竟功能够用，且更轻更稳定

**Comment by baixin513** [comment]
感谢反馈！我们当前支持的是一些主流的云厂商，您反馈的平台我们可以先进行一下需求收集，若用户需求强烈程度，我们会进行综合考虑。

**Comment by baixin513** [comment]
我们先调研一下PVE平台，若可行将规划在v1.3.0版本支持一下。

**Comment by vipsql** [comment]
PVE平台的统一管理需求还是比较强烈

**Comment by baixin513** [comment]
感谢大家反馈，该PVE已在V1.3.0版本中支持，欢迎试用。

**Comment by charnet1019** [comment]
oVirt是否有支持的计划？
