### ISSUE TITLE
[BUG][安全合规][阿里云][扫描检查]资源检测结果中没有显示资源ID、资源名称

### ISSUE THREAD

**Issue by liuxinxin2020** [CloudExplorer-Dev/CloudExplorer-Lite#80]
### CloudExplorer Lite 版本

v1.0.0

### 问题描述

资源检测页面没有显示资源ID、资源名称
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/72063838/233841541-dfa9b699-0bda-4c05-9596-df2e35a29344.png">

### 重现步骤

一、设置如下图所示的规则
二、执行一键扫描
三、查看上述规则对应的扫描详情
<img width="868" alt="image" src="https://user-images.githubusercontent.com/72063838/233841594-6bdeacbe-5a79-44a5-b6d4-209d008edf51.png">

**Comment by Shenguobin0102** [comment]
感谢反馈，已确认问题，后续版本规划修复，请关注后续版本。

**Comment by baixin513** [comment]
该issue在v1.1.0版本中已解决。
