### ISSUE TITLE
[BUG][云账单][阿里云][分账设置]分账规则页面中云账号的名称没有随管理中心云账号列表名称的修改而修改

### ISSUE THREAD

**Issue by liuxinxin2020** [CloudExplorer-Dev/CloudExplorer-Lite#81]
### CloudExplorer Lite 版本

v1.0.0

### 问题描述

1、修改管理中心云账号列表中云账号的名称；
2、到账单的分账设置页面进行分账规则设置；
3、分账规则选择云账号时，发现显示的云账号名称还是管理中心云账号列表中修改之前的名称。
<img width="1390" alt="image" src="https://user-images.githubusercontent.com/72063838/233842168-5bd47b3d-0c14-4632-b2e0-36d63bbd7c01.png">
<img width="1377" alt="image" src="https://user-images.githubusercontent.com/72063838/233842183-cdd89fab-a8d5-4bae-a201-91001fcf2701.png">

### 重现步骤

如问题描述

**Comment by Shenguobin0102** [comment]
感谢反馈，已确认问题，请关注后续版本

**Comment by baixin513** [comment]
当前云账单模块是读取缓存数据，管理中心云账号名称变更以及组织/工作空间名称的变更，云账单模块都无法感知，我们需要在管理中心增加一个公用数据变更的通知机制，该功能处理改动有些多。我们将规划到功能版本中实现，请关注后续版本发布。

**Comment by baixin513** [comment]
该issue在v1.1.0版本中已解决。
