### ISSUE TITLE
[openstack]创建机器时，原来的卷如果是没有设置类型，就不能继续

### ISSUE THREAD

**Issue by bio-lin** [CloudExplorer-Dev/CloudExplorer-Lite#83]
### CloudExplorer Lite 版本

1.01

### 请描述您的需求或者改进建议

如果本身openstack上的卷没有设置类型，使用云管平台创建时就不能跳过卷的类型直接创建，提示磁盘类型不能为空

**Comment by baixin513** [comment]
感谢反馈，创建OpenStack云主机和添加磁盘页面的磁盘类型增加 Null的选项。 若没有设置卷的类型可以选择Null属性。

**Comment by baixin513** [comment]
该issue 已在v1.1.0版本中解决
