### ISSUE TITLE
[BUG][安全合规][云厂商][扫描检查]建完一个规则后，扫描检查列表中的扫描结果和点进去看的扫描结果不一致

### ISSUE THREAD

**Issue by supersarah123** [CloudExplorer-Dev/CloudExplorer-Lite#85]
### CloudExplorer Lite 版本

v1.0.0

### 问题描述

建完一个规则后，扫描检查列表中的扫描结果和点进去看的扫描结果不一致，外部列表显示检测状态为合规，且不合规资源为0，但是点击扫描结果，存在不合规的资源

### 重现步骤

<img width="1108" alt="image" src="https://user-images.githubusercontent.com/45278450/233895921-fc4ad7cf-f014-4f2f-bb25-bc387557f577.png"><img width="1095" alt="image" src="https://user-images.githubusercontent.com/45278450/233895940-a6ba5446-e2ec-4075-97bc-8a447cedaae2.png">

### 期待的正确结果

希望建完规则后能立即进行扫描，且列表中的结果和扫描结果中一致

**Comment by Shenguobin0102** [comment]
感谢反馈，我们讨论后回复。

**Comment by Shenguobin0102** [comment]
已确认问题，在后续版本修复，请关注后续版本
