### ISSUE TITLE
[BUG]系统有时无法登录

### ISSUE THREAD

**Issue by supersarah123** [CloudExplorer-Dev/CloudExplorer-Lite#89]
### CloudExplorer Lite 版本

v1.0.0

### 问题描述

系统登录页面输入用户名密码后点击登录，系统没反应，多次点击登录，仍然没有反应，登录不上系统。刷新下浏览器或者再重开一个浏览器页面，再进行登录才可以登录进去。

### 重现步骤

1.访问登录页面
2.输入正确的用户名密码
3.点击登录

**Comment by Shenguobin0102** [comment]
感谢反馈，已确认问题，请关注后续版本。

**Comment by baixin513** [comment]
该issue在v1.1.0版本中已解决。
