### ISSUE TITLE
安全合规模块-丰富合规规则种类

### ISSUE THREAD

**Issue by liuxinxin2020** [CloudExplorer-Dev/CloudExplorer-Lite#9]
### CloudExplorer Lite 版本

v1.0.0

### 请描述您的需求或者改进建议

支持设置如下合规规则：
判断各类公有云云磁盘是否设置了备份策略；
云平台：阿里云、华为云、腾讯云

**Comment by baixin513** [comment]
感谢反馈，安全合规的规则库会不断丰富增加的，请关注下后续版本。
