### ISSUE TITLE
[FEATURE][云计费]支持私有云资源的计费功能

### ISSUE THREAD

**Issue by xiaoluoge11** [CloudExplorer-Dev/CloudExplorer-Lite#97]
### CloudExplorer Lite 版本

	v1.0.1

### 请描述您的需求或者改进建议

我这边是只有运行的私有云，openstack，想实现私有云命名空间下租户，使用了多少资源，产生了多少计费账单

### 请描述你建议的实现方案

可以让用户自定义计费的相关账单比如：CPU、内存、带宽、磁盘多少钱，然后根据用户计算出对应的账单，这个功能需求我参考了zstack

**Comment by renziyou** [comment]
这个功能好呀，一定要支持哈，希望能快些开发

**Comment by xiaoluyahei** [comment]
希望也可以对VMWare支持此功能，十分有用！！！！

**Comment by bigbird1985** [comment]
一定要支持啊，非常有用！！！

**Comment by baixin513** [comment]
感谢大家的建议，该需求我们规划v1.2.0版本支持。

**Comment by baixin513** [comment]
该功能在V1.2.0中实现，欢迎试用
