### ISSUE TITLE
期望支持kvm虚拟机管理

### ISSUE THREAD

**Issue by zhenliangliang** [CloudExplorer-Dev/CloudExplorer-Lite#98]
### CloudExplorer Lite 版本

v1.0.1

### 请描述您的需求或者改进建议

能够管理kvm虚拟机

**Comment by baixin513** [comment]
感谢，我们当前支持的是一些主流的云平台如：华为云、腾讯云、阿里云、VMware、OpenStack。 KVM管理暂时没有规划到计划内，后期有计划将 扩展云平台整理成插件方式，您可以考虑二次开发云平台插件。
